-- Enterprise User Management Mock Seed Data for PostgreSQL
-- Covers: Active users, Pending Activation (first-login stage), Suspended accounts, and Legacy migrated users.

INSERT INTO enterprise_users (
    id, external_identity_id, username, email, first_name, last_name,
    date_of_birth, phone_number, status, street, city, state, zip_code, country,
    department, employee_id, preferred_language, newsletter_opt_in, created_at, updated_at
) VALUES
-- 1. Primary Demo User: Alex Morgan (Active, Security & Identity)
(
    'usr-1001',
    '00u1abcd234EFGH567',
    'alex.morgan@enterprise.com',
    'alex.morgan@enterprise.com',
    'Alex',
    'Morgan',
    '1992-05-14',
    '+1 (555) 019-2834',
    'ACTIVE',
    '100 Enterprise Way, Suite 400',
    'San Francisco',
    'CA',
    '94105',
    'US',
    'Security & Identity',
    'EMP-90210',
    'en',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '30 days',
    CURRENT_TIMESTAMP
),
-- 2. Sarah Connor (Active, Cloud Infrastructure & DevOps)
(
    'usr-1002',
    '00u2bcde345FGHI678',
    'sarah.connor@enterprise.com',
    'sarah.connor@enterprise.com',
    'Sarah',
    'Connor',
    '1988-11-23',
    '+1 (555) 028-4921',
    'ACTIVE',
    '450 Tech Ridge Blvd',
    'Austin',
    'TX',
    '78753',
    'US',
    'DevOps & Cloud',
    'EMP-84721',
    'en',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '25 days',
    CURRENT_TIMESTAMP
),
-- 3. Marcus Chen (Pending Activation - Greenfield Profile Registration Flow)
(
    'usr-1003',
    '00u3cdef456GHIJ789',
    'marcus.chen@enterprise.com',
    'marcus.chen@enterprise.com',
    'Marcus',
    'Chen',
    '1995-03-08',
    '+1 (555) 037-8812',
    'PENDING_ACTIVATION',
    '120 Wall Street, Floor 18',
    'New York',
    'NY',
    '10005',
    'US',
    'Financial Technology',
    'EMP-71932',
    'en',
    FALSE,
    CURRENT_TIMESTAMP - INTERVAL '2 days',
    CURRENT_TIMESTAMP
),
-- 4. Elena Rostova (Active, Artificial Intelligence & Machine Learning)
(
    'usr-1004',
    '00u4defg567HIJK890',
    'elena.rostova@enterprise.com',
    'elena.rostova@enterprise.com',
    'Elena',
    'Rostova',
    '1990-09-17',
    '+1 (555) 046-1190',
    'ACTIVE',
    '800 Bellevue Way NE',
    'Seattle',
    'WA',
    '98004',
    'US',
    'AI / Machine Learning',
    'EMP-62914',
    'en',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '15 days',
    CURRENT_TIMESTAMP
),
-- 5. David Kim (Suspended - Security Compliance Flag)
(
    'usr-1005',
    '00u5efgh678IJKL901',
    'david.kim@enterprise.com',
    'david.kim@enterprise.com',
    'David',
    'Kim',
    '1985-07-30',
    '+1 (555) 055-6734',
    'SUSPENDED',
    '233 S Wacker Dr',
    'Chicago',
    'IL',
    '60606',
    'US',
    'HR Operations',
    'EMP-51092',
    'en',
    FALSE,
    CURRENT_TIMESTAMP - INTERVAL '40 days',
    CURRENT_TIMESTAMP - INTERVAL '5 days'
),
-- 6. Priya Patel (Pending Activation - New Onboarding)
(
    'usr-1006',
    '00u6fghi789JKLM012',
    'priya.patel@enterprise.com',
    'priya.patel@enterprise.com',
    'Priya',
    'Patel',
    '1993-12-05',
    '+44 20 7946 0912',
    'PENDING_ACTIVATION',
    '25 Bank Street, Canary Wharf',
    'London',
    'Greater London',
    'E14 5JP',
    'GB',
    'Enterprise Architecture',
    'EMP-43891',
    'en',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '1 day',
    CURRENT_TIMESTAMP
),
-- 7. James Wilson (Active - Legacy Migrated User)
(
    'usr-1007',
    'LEGACY_USER_7788',
    'james.wilson@enterprise.com',
    'james.wilson@enterprise.com',
    'James',
    'Wilson',
    '1982-01-19',
    '+1 (555) 064-9022',
    'ACTIVE',
    '161 Bay Street, Suite 2700',
    'Toronto',
    'ON',
    'M5J 2S1',
    'CA',
    'Legal & Compliance',
    'EMP-30419',
    'en',
    FALSE,
    CURRENT_TIMESTAMP - INTERVAL '90 days',
    CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    department = EXCLUDED.department,
    updated_at = CURRENT_TIMESTAMP;
